name: weather_watcher
description: A reusable Flutter-compatible package that provides temperature and humidity data from BLE sensors, local IoT sensors, or remote weather APIs.
version: 0.0.1
homepage: https://alpenlogic.com
publish_to: none # Remove this line if you decide to publish on pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  location: ^8.0.0
  http: ^1.1.0
  flutter_reactive_ble: ^5.4.0  # or latest
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter