name: weather_watcher
description: A reusable Flutter-compatible package that provides temperature and humidity data from BLE sensors, local IoT sensors, or remote weather APIs.
version: 0.0.1
homepage: https://alpenlogic.com
publish_to: none # Remove this line if you decide to publish on pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter